"""Build tool-specific adapters from the Brain's canonical, model-neutral sources.

Canonical (edit these)                 Generated (never edit by hand)
  07-Agents/<name>/profile.md     ->     .claude/agents/<name>.md        Claude Code subagent
                                         .gemini/agents/<name>.md        Gemini CLI subagent
  00-System/skills/<name>/        ->     .claude/skills/<name>/          Claude Code skill
                                         .agents/skills/<name>/          Gemini CLI skill (vendor-neutral alias)
  (<name>.md becomes SKILL.md in every skill adapter)

Usage, from the Brain root:
  python 00-System/scripts/build_adapters.py            write every adapter
  python 00-System/scripts/build_adapters.py --check    exit 1 if any adapter is stale, missing or orphaned
  python 00-System/scripts/build_adapters.py --prune    also delete orphaned generated adapters
  python 00-System/scripts/build_adapters.py --adopt    overwrite a hand-written file that sits where an
                                                        adapter goes (move its content to the source first)
  python 00-System/scripts/build_adapters.py --package edit-clock --out <folder>
                                                        zip one skill for upload to claude.ai

The neutral vocabulary (tiers, tool names) and the write tiers are defined in 00-System/portability.md.
To link a new AI tool, verify its agent and skill formats in its own docs, then add a TARGETS entry.
"""
import argparse
import sys
import zipfile
from pathlib import Path

BRAIN = Path(__file__).resolve().parents[2]
AGENTS_DIR = BRAIN / "07-Agents"
SKILLS_DIR = BRAIN / "00-System" / "skills"
MARK = "GENERATED by 00-System/scripts/build_adapters.py"
SKILL_KEYS = ("name", "description", "allowed-tools")  # Agent Skills fields carried into SKILL.md
CLAUDE_AI_SKILL_ROOT = "/mnt/skills/user/"  # where claude.ai mounts an uploaded skill

# Each target maps the neutral vocabulary to one tool. A neutral tool with no mapping is dropped and
# named in the agent's prompt as unavailable. A tier mapped to None omits `model` (the tool's default).
TARGETS = {
    "claude-code": {
        "role": "primary",
        "agents_dir": ".claude/agents",
        "skills_dir": ".claude/skills",
        "tiers": {"light": "haiku", "standard": "sonnet", "strong": "opus"},
        "tools": {
            "read": ["Read", "Glob", "Grep"],
            "write": ["Write", "Edit"],
            "shell": ["Bash"],
            "send-file": ["SendUserFile"],
            "web": ["WebFetch", "WebSearch"],
        },
        "mcp_servers": {"davinci-resolve": "DaVinci_Resolve"},
        "mcp_name": "mcp__{server}__{tool}",
        "tools_format": "csv",
        "extra_fields": [],
    },
    # Verified against the installed Gemini CLI 0.60.0 docs (docs/core/subagents.md, docs/cli/creating-skills.md,
    # docs/tools/*.md), 2026-09-22. No MCP servers are connected in Gemini yet.
    "gemini-cli": {
        "role": "guest",
        "tool_label": "gemini",
        "agents_dir": ".gemini/agents",
        "skills_dir": ".agents/skills",
        "tiers": {"light": None, "standard": None, "strong": None},
        "tools": {
            "read": ["read_file", "list_directory", "glob", "grep_search"],
            "write": ["write_file", "replace"],
            "shell": ["run_shell_command"],
            "web": ["web_fetch", "google_web_search"],
        },
        "mcp_servers": {},
        "mcp_name": "mcp_{server}_{tool}",
        "tools_format": "yaml-list",
        "extra_fields": ["kind: local"],
    },
}


def fail(msg):
    sys.exit(f"build_adapters: {msg}")


def rel(p):
    return Path(p).relative_to(BRAIN).as_posix()


def split_frontmatter(path):
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    if not text.startswith("---\n") or "\n---\n" not in text[3:]:
        fail(f"{rel(path)} has no frontmatter")
    end = text.index("\n---\n", 3)
    return text[4:end], text[end + 5:]


def fm_blocks(fm):
    """Top-level frontmatter keys -> raw text (key line plus indented continuation lines)."""
    blocks, key = {}, None
    for line in fm.split("\n"):
        if line and not line[0].isspace() and ":" in line:
            key = line.split(":", 1)[0].strip()
            blocks[key] = line
        elif key:
            blocks[key] += "\n" + line
    return blocks


def fm_value(block):
    return block.split(":", 1)[1].strip().strip("\"'")


def fm_list(block):
    v = fm_value(block)
    if not (v.startswith("[") and v.endswith("]")):
        fail(f"expected an inline list like [a, b], got: {v}")
    return [x.strip() for x in v[1:-1].split(",") if x.strip()]


def read_profile(profile):
    fm, body = split_frontmatter(profile)
    b = fm_blocks(fm)
    missing = [k for k in ("name", "description", "tier", "tools") if k not in b]
    if missing:
        fail(f"{rel(profile)} frontmatter needs {missing} (see 00-System/templates/agent-profile.md)")
    tier = fm_value(b["tier"])
    if tier not in ("light", "standard", "strong"):
        fail(f"{rel(profile)}: unknown tier '{tier}' (use light, standard or strong)")
    return b, fm_value(b["name"]), tier, fm_list(b["tools"]), body


def map_tools(neutral, t, where):
    granted, unavailable = [], []
    for n in neutral:
        if n.startswith("mcp:"):
            parts = n.split(":")
            if len(parts) != 3:
                fail(f"{where}: '{n}' - use mcp:<server>:<tool>")
            server = t["mcp_servers"].get(parts[1])
            if server:
                granted.append(t["mcp_name"].format(server=server, tool=parts[2]))
            elif f"the {parts[1]} MCP server" not in unavailable:
                unavailable.append(f"the {parts[1]} MCP server")
        elif n in t["tools"]:
            granted += t["tools"][n]
        elif n in TARGETS["claude-code"]["tools"]:  # a known neutral tool this target lacks
            unavailable.append(f"`{n}`")
        else:
            fail(f"{where}: unknown tool '{n}' (see the tools table in 00-System/portability.md)")
    return granted, unavailable


def build_agent(profile, tname, t):
    b, name, tier, neutral, body = read_profile(profile)
    granted, unavailable = map_tools(neutral, t, rel(profile))
    head = ["---", b["name"], b["description"], *t["extra_fields"]]
    if t["tiers"][tier]:
        head.append(f"model: {t['tiers'][tier]}")
    if t["tools_format"] == "csv":
        head.append(f"tools: {', '.join(granted)}")
    else:
        head += ["tools:"] + [f"  - {g}" for g in granted]
    head.append("---")
    folder = rel(profile.parent)
    intro = [
        f"<!-- {MARK} from {folder}/profile.md for {tname}. Edit the profile, then re-run the script. -->",
        "",
        f"You are the **{name}** agent in Samuel's Brain. AGENTS.md is the constitution and overrides anything here.",
        "",
    ]
    if t["role"] == "guest":
        intro += [
            f"**You are running in {tname} as a guest** (00-System/portability.md, write tiers). Unless Samuel widens it "
            f"for this session, write only to `01-Inbox/` and `06-Logs/`, and prefix commits `[{t['tool_label']}]`. Where "
            f"the profile below says to write elsewhere - including this agent's log and memory - write it as a note in "
            f"`01-Inbox/` instead, and the primary AI will file it.",
            "",
        ]
    if unavailable:
        intro += [
            f"**Not available in {tname}:** {', '.join(unavailable)}. If a step needs one, say so and stop at that step. "
            f"Do not improvise around it. Without `send-file`, give Samuel the full path.",
            "",
        ]
    intro += [
        f"Before acting, read `{folder}/memory.md` - what this agent has already learned. Log every action to "
        f"`{folder}/log.md` and record anything newly learned in `memory.md` (both append-only, dated, newest at the "
        f"bottom). Read only what the current step needs.",
        "",
        "Your profile follows. It is the source of truth for your mission, scope, limits and what to ask before.",
        "",
        "",
    ]
    text = "\n".join(head) + "\n\n" + "\n".join(intro) + body.lstrip("\n")
    return {f"{t['agents_dir']}/{name}.md": text.encode("utf-8")}


def skill_files(skill_dir):
    """The tool-neutral SKILL.md form of one skill, keyed by path inside the skill folder."""
    name = skill_dir.name
    src = skill_dir / f"{name}.md"
    if not src.exists():
        fail(f"{rel(skill_dir)} needs its main file named {name}.md")
    fm, body = split_frontmatter(src)
    b = fm_blocks(fm)
    if "description" not in b or fm_value(b.get("name", "name:")) != name:
        fail(f"{rel(src)} frontmatter needs name: {name} and a description")
    head = "\n".join(["---"] + [b[k] for k in SKILL_KEYS if k in b] + ["---"])
    note = f"\n<!-- {MARK} from {rel(src)}. Edit the source, then re-run the script. -->\n"
    out = {"SKILL.md": (head + note + body).encode("utf-8")}
    for p in sorted(skill_dir.rglob("*")):
        if p.is_file() and p != src:
            out[p.relative_to(skill_dir).as_posix()] = p.read_bytes()
    return out


def runs_as_main_session(profile):
    """True for a profile the main session plays (the orchestrator). Subagents cannot launch subagents,
    so such a profile gets no native subagent file. It is still validated."""
    b, *_ = read_profile(profile)
    return "runs-as" in b and fm_value(b["runs-as"]) == "main-session"


def expected():
    out = {}
    profiles = sorted(p for p in AGENTS_DIR.glob("*/profile.md") if not runs_as_main_session(p))
    skills = sorted(p for p in SKILLS_DIR.iterdir() if p.is_dir())
    for tname, t in TARGETS.items():
        for profile in profiles:
            out.update(build_agent(profile, tname, t))
        for d in skills:
            for k, v in skill_files(d).items():
                out[f"{t['skills_dir']}/{d.name}/{k}"] = v
    return out


def generated_on_disk():
    """Every file a previous run generated (identified by the MARK)."""
    found = set()
    for t in TARGETS.values():
        for f in (BRAIN / t["agents_dir"]).glob("*.md"):
            if MARK in f.read_text(encoding="utf-8"):
                found.add(rel(f))
        for skill_md in (BRAIN / t["skills_dir"]).glob("*/SKILL.md"):
            if MARK in skill_md.read_text(encoding="utf-8"):
                found.update(rel(p) for p in skill_md.parent.rglob("*") if p.is_file())
    return found


def package(name, out_dir):
    d = SKILLS_DIR / name
    if not d.is_dir():
        fail(f"no skill at {rel(d)}")
    out_dir.mkdir(parents=True, exist_ok=True)
    zpath = out_dir / f"{name}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for key, data in skill_files(d).items():
            if key == "SKILL.md":
                data = data.decode("utf-8").replace(f"00-System/skills/{name}/",
                                                    f"{CLAUDE_AI_SKILL_ROOT}{name}/").encode("utf-8")
            z.writestr(f"{name}/{key}", data)
    print(f"packaged {name} -> {zpath}")


def remove_empty_dirs():
    for t in TARGETS.values():
        root = BRAIN / t["skills_dir"]
        for d in sorted((p for p in root.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True):
            if not any(d.iterdir()):
                d.rmdir()


def main():
    ap = argparse.ArgumentParser(description="Build tool adapters from the Brain's canonical sources.")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--prune", action="store_true")
    ap.add_argument("--adopt", action="store_true")
    ap.add_argument("--package")
    ap.add_argument("--out", type=Path)
    a = ap.parse_args()

    if a.package:
        if not a.out:
            fail("--package needs --out <folder> (outside the Brain)")
        return package(a.package, a.out)

    want, have = expected(), generated_on_disk()
    stale = [k for k, v in want.items() if (BRAIN / k).exists() and (BRAIN / k).read_bytes() != v]
    missing = [k for k in want if not (BRAIN / k).exists()]
    orphans = sorted(have - set(want))
    handwritten = [k for k in stale if k not in have]  # exists, differs, and no MARK: a person wrote it

    if a.check:
        for label, items in (("stale", stale), ("missing", missing), ("orphaned", orphans)):
            for k in items:
                print(f"{label}: {k}")
        ok = not (stale or missing or orphans)
        print("adapters up to date" if ok else "adapters out of date - run build_adapters.py")
        sys.exit(0 if ok else 1)

    if handwritten and not a.adopt:
        fail("hand-written file(s) sit where adapters go - move their content into the canonical "
             "source, then re-run with --adopt:\n  " + "\n  ".join(handwritten))
    for k in stale + missing:
        target = BRAIN / k
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(want[k])
    for k in orphans:
        if a.prune:
            (BRAIN / k).unlink()
        else:
            print(f"orphaned (re-run with --prune to delete): {k}")
    if a.prune:
        remove_empty_dirs()
    print(f"adapters: {len(want)} expected, {len(stale) + len(missing)} written, "
          f"{len(orphans)} orphaned{' (pruned)' if a.prune and orphans else ''}")


if __name__ == "__main__":
    main()
