#!/usr/bin/env bash
# Regenerates PA.md — the single-file context bundle that the Claude PA project reads.
# Run this before any commit that touches CLAUDE.md, REMOTE.md, context/ or .claude/.
set -euo pipefail
cd "$(dirname "$0")/.."

out=PA.md
tmp="$(mktemp)"

emit() {
  local f="$1"
  [ -f "$f" ] || return 0
  printf '\n\n---\n\n## FILE: %s\n\n' "$f"
  cat "$f"
}

{
  printf '# Engine — full context bundle\n\n'
  printf 'Generated %s (WAT) from commit %s.\n' "$(TZ=Africa/Lagos date '+%Y-%m-%d %H:%M')" "$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
  printf 'The commit shown is the one *before* this bundle was written, so the bundle is one commit newer than it says.\n\n'
  printf 'DO NOT EDIT THIS FILE. It is generated by `tools/bundle.sh` by concatenating the\n'
  printf 'files listed below. Edits here are overwritten and never reach the engine.\n\n'
  printf 'Contents: operating rules, remote setup, all of `context/`, the enforcer agent,\n'
  printf 'and every check-in skill.\n'

  emit CLAUDE.md
  emit REMOTE.md
  # context/*.md only — context/ledger-notes/ is DELIBERATELY excluded. It is the
  # raw daily narrative, it grows every day forever, and the project reads the
  # compact ledger scoreboard instead. Do not add it.
  for f in context/*.md; do emit "$f"; done
  for f in .claude/agents/*.md; do emit "$f"; done
  for f in .claude/skills/*/SKILL.md; do emit "$f"; done
} > "$tmp"

mv "$tmp" "$out"
echo "wrote $out ($(wc -c < "$out") bytes)"
