// Samuel's verdicts, round 1 (2026-09-30, pasted from the gallery's "Copy my review"). [verdict, his note, what changed in v2]
window.VERDICTS = {
  round: 2,
  reviewed: "2026-09-30",
  items: {
    P01: ["approve"],
    P02: ["approve", "Just don't use that background wave", "Background wave removed; on BGORANGE"],
    P03: ["approve"],
    P04: ["approve"],
    P05: ["change", "I love this, but make it appear from the buttom instead if it's on screen, but we can use this in different other places", "Rises from the bottom over the A-roll. The top version stays as an option for other places"],
    P06: ["todo"],
    P07: ["change", "I love this, but I want a consistent background, so, not this grey background, but the Pill is okay", "Same pill, now on BGORANGE"],
    P08: ["approve"],
    P09: ["change", "I prefer a bar that fills up instead of the dots", "The dots are gone: one bar fills, with a glowing head"],
    P10: ["change", "I love this, but let it be on the orangeBG background", "On BGORANGE"],
    P11: ["approve"],
    P12: ["drop"],
    P13: ["approve"],
    B01: ["approve", "", "Background now exact BGORANGE"],
    B02: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    B03: ["change", "Make it one card, not multiple", "One card: the big number, two side stats and the pipeline line inside a single panel"],
    B04: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    B05: ["approve", "", "Background now exact BGORANGE"],
    B06: ["drop"],
    B07: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    B08: ["change", "Love this but Would prefer quotes to be on a picture/video of the person quoting it", "The quote now sits on the speaker's own footage (Alex, with a real line from his Apollo script)"],
    C01: ["change", "I like this but I don't normally use this kind of in Animation, and I don't like the rotation", "No rotation and no 3D: flat glass cards slide up"],
    C02: ["change", "I always prefer this smaller, too big on the screen right now", "About a third smaller"],
    C03: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    C04: ["change", "Love this but The background must be BGorange", "On BGORANGE (reflections kept, floor removed)"],
    C05: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    C06: ["approve", "", "Background now exact BGORANGE"],
    C07: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    C08: ["approve"],
    O01: ["change", "Love this but The background must be BGorange", "On BGORANGE"],
    O02: ["change", "Love this but The background must be BGorange", "On BGORANGE: white hub, faint rings, orange pulse"],
    O03: ["approve", "", "Background now exact BGORANGE"],
    O04: ["approve", "", "Background now exact BGORANGE"],
    O05: ["change", "Love this but The background must be BGorange", "On BGORANGE: white number, faint track"],
    O06: ["approve"],
    O07: ["change", "Love this but The background must be BGorange", "On BGORANGE: white and orange outlines, orange overlap"],
    O08: ["drop"],
    O09: ["approve"],
    O10: ["approve"],
  },
};
